cluster:
  name: {{ .CLUSTER_NAME }}
  version: 1.14
  roleArn: {{ .ROLE_ARN }}
  resourcesvpconfig:
    endpointpublicaccess: true
    publicaccesscidrs:
      {{ range $cidr := get_range .PUBLIC_CIDRS .SEPERATOR }}
      - {{ $cidr }}
      {{ end }}
    subnetids:
      {{ range $subnet_id := get_range .SUBNET_IDS .SEPERATOR }}
      - {{ $subnet_id }}
      {{ end }}
nodegroups:
  - nodegroupname: main-node
    noderole: {{ .NODE_ROLE }}
    disksize: 300
    instancetypes:
      - t3.medium
    scalingconfig:
      desiredsize: 1
      maxsize: 1
      minsize: 1
    labels:
      aws.amazon.com/eks-nodegroup: main-node


    