cluster:
  name: {{ .CLUSTER_NAME }}
  version: 1.14
  rolearn: {{ .ROLE_ARN }}
  resourcesvpcconfig:
    endpointpublicaccess: true
    subnetids:
      {{ range $subnetId := get_range .SUBNET_IDS .SEPERATOR }}
      - {{ $subnetId }}
      {{ end }}
nodegroups:
  - nodegroupname: main-node
    noderole: {{ .NODE_ROLE }}
    disksize: 300
    subnets:
      {{ range $subnetId := get_range .SUBNET_IDS .SEPERATOR }}
      - {{ $subnetId }}
      {{ end }}
    instancetypes:
      - t3.medium
    scalingconfig:
      desiredsize: 1
      maxsize: 1
      minsize: 1
    labels:
      node-name: main-node


    