cluster:
  name: {{ .CLUSTER_NAME }}
nodegroups:
  - nodegroupname: prometheus-{{ .PR_NUMBER }}
    noderole: {{ .NODE_ROLE }}
    disksize: 100
    subnets:
      {{ range $subnetId := get_range .SUBNET_IDS .SEPERATOR }}
      - {{ $subnetId }}
      {{ end }}
    instancetypes:
      - t3.medium #change this so it matches with gke 
    scalingconfig:
      desiredsize: 2
      maxsize: 2
      minsize: 2
    labels:
      isolation: prometheus
      node-name: prometheus-{{ .PR_NUMBER }}
  - nodegroupname: nodes-{{ .PR_NUMBER }}
    noderole: {{ .NODE_ROLE }}
    disksize: 100
    subnets:
      {{ range $subnetId := get_range .SUBNET_IDS .SEPERATOR }}
      - {{ $subnetId }}
      {{ end }}
    instancetypes:
      - t3.medium #change this so it matches with gke
    scalingconfig:
      desiredsize: 1
      maxsize: 1
      minsize: 1
    labels:
      isolation: none
      node-name: nodes-{{ .PR_NUMBER }}
    

